[
  {
    "vacancy_number": "ADB-001/25",
    "title": "UI/UX Designer",
    "job_grade": "XI",
    "company": "Addis Bank S.C",
    "category": 1,
    "location": "Addis Ababa, Ethiopia",
    "field_of_studies": ["UI Design", "Human-Centered Design"],
    "job_type": "Full-time",
    "salary": "Competitive",
    "description": "Design intuitive and modern UI for digital banking platforms.",
    "application_deadline": "2025-08-15",
    "post_date": "2025-07-07",
    "show_experience": true,
    "status": "Published",
    "details": [
      { "detail_type": "Responsibility", "description": "Create user-friendly UI designs for web and mobile." },
      { "detail_type": "Responsibility", "description": "Collaborate with product and dev teams to refine designs." },
      { "detail_type": "Skill", "description": "Adobe XD, Figma, Sketch proficiency." },
      { "detail_type": "Skill", "description": "Strong understanding of responsive design." },
      { "detail_type": "Qualification", "description": "Bachelor’s in Design, HCI, or related." },
      { "detail_type": "Qualification", "description": "Portfolio of UI/UX projects." },
      { "detail_type": "Benefit", "description": "Flexible work hours and remote options." },
      { "detail_type": "Benefit", "description": "Health insurance and performance bonuses." }
    ]
  },
  {
    "vacancy_number": "ADB-002/25",
    "title": "ICT Support Officer",
    "job_grade": "X",
    "company": "Addis Bank S.C",
    "category": 3,
    "location": "Hawassa, Ethiopia",
    "field_of_studies": ["Information Technology", "Computer Science"],
    "job_type": "Full-time",
    "salary": "As per company scale",
    "description": "Provide hardware and software support across all departments.",
    "application_deadline": "2025-08-20",
    "post_date": "2025-07-08",
    "show_experience": true,
    "status": "Active",
    "details": [
      { "detail_type": "Responsibility", "description": "Install and maintain IT equipment." },
      { "detail_type": "Responsibility", "description": "Provide technical assistance to staff." },
      { "detail_type": "Skill", "description": "Strong knowledge of Windows Server and networking." },
      { "detail_type": "Skill", "description": "Troubleshooting hardware and software issues." },
      { "detail_type": "Qualification", "description": "Degree in IT or related field." },
      { "detail_type": "Benefit", "description": "Company mobile allowance." },
      { "detail_type": "Benefit", "description": "Pension and overtime pay." }
    ]
  },
  {
    "vacancy_number": "ADB-003/25",
    "title": "Finance Officer",
    "job_grade": "XI",
    "company": "Addis Bank S.C",
    "category": 4,
    "location": "Adama, Ethiopia",
    "field_of_studies": ["Accounting", "Finance"],
    "job_type": "Full-time",
    "salary": "Negotiable",
    "description": "Manage financial records and assist with internal audits.",
    "application_deadline": "2025-08-25",
    "post_date": "2025-07-09",
    "show_experience": true,
    "status": "Published",
    "details": [
      { "detail_type": "Responsibility", "description": "Prepare monthly financial statements." },
      { "detail_type": "Responsibility", "description": "Support audit and compliance processes." },
      { "detail_type": "Skill", "description": "Proficiency in ERP systems and Excel." },
      { "detail_type": "Skill", "description": "Strong analytical and reporting skills." },
      { "detail_type": "Qualification", "description": "BA in Accounting or Finance." },
      { "detail_type": "Benefit", "description": "Yearly bonus and health coverage." }
    ]
  },
  {
    "vacancy_number": "ADB-004/25",
    "title": "Content Researcher",
    "job_grade": "IX",
    "company": "Addis Bank S.C",
    "category": 5,
    "location": "Mekelle, Ethiopia",
    "field_of_studies": ["Journalism", "Library Science", "Research"],
    "job_type": "Contract",
    "salary": "Based on experience",
    "description": "Conduct content audits and research for publication.",
    "application_deadline": "2025-08-18",
    "post_date": "2025-07-09",
    "show_experience": false,
    "status": "Draft",
    "details": [
      { "detail_type": "Responsibility", "description": "Gather and analyze internal reports." },
      { "detail_type": "Responsibility", "description": "Research relevant banking topics." },
      { "detail_type": "Skill", "description": "Research, analysis, and presentation skills." },
      { "detail_type": "Qualification", "description": "Degree in Journalism or related field." },
      { "detail_type": "Benefit", "description": "Flexible working hours." }
    ]
  },
  {
    "vacancy_number": "ADB-005/25",
    "title": "Branch Auditor",
    "job_grade": "XII",
    "company": "Addis Bank S.C",
    "category": 4,
    "location": "Dire Dawa, Ethiopia",
    "field_of_studies": ["Accounting", "Auditing"],
    "job_type": "Full-time",
    "salary": "As per bank scale",
    "description": "Audit branch operations and ensure regulatory compliance.",
    "application_deadline": "2025-08-30",
    "post_date": "2025-07-10",
    "show_experience": true,
    "status": "Under Review",
    "details": [
      { "detail_type": "Responsibility", "description": "Conduct periodic audits of branches." },
      { "detail_type": "Responsibility", "description": "Verify compliance with internal policies." },
      { "detail_type": "Skill", "description": "Knowledge of auditing standards and tools." },
      { "detail_type": "Qualification", "description": "Bachelor’s degree in Accounting or Auditing." },
      { "detail_type": "Benefit", "description": "Fuel allowance and housing support." }
    ]
  }
]
