# Generated by Django 5.2.1 on 2025-06-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicant_cgpa_alter_applicant_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='selectedCriteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.criteria'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('SMS_Sent', 'SMS_Sent'), ('Interview Scheduled', 'Interview Scheduled'), ('Interviewed', 'Interviewed'), ('Assessment Pending', 'Assessment Pending'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Hired', 'Hired'), ('On Hold', 'On Hold'), ('Waitlisted', 'Waitlisted'), ('Background Check', 'Background Check')], default='Pending', max_length=50),
        ),
    ]
