# Generated by Django 5.2.1 on 2025-06-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
