# Generated by Django 5.2.1 on 2025-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_criteria_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
