# Generated by Django 5.2.1 on 2025-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicant_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='program',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Distance', 'Distance'), ('Extension', 'Extension')], default='Pending', max_length=50),
        ),
    ]
