# Generated by Django 5.2.1 on 2025-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0004_applicantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
