# Generated by Django 5.2.1 on 2025-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0006_applicantuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
