# Generated by Django 5.0.4 on 2025-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interviewed', 'Interviewed'), ('Assessment Pending', 'Assessment Pending'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Hired', 'Hired'), ('On Hold', 'On Hold'), ('Waitlisted', 'Waitlisted'), ('Background Check', 'Background Check')], default='Pending', max_length=50),
        ),
    ]
