# Generated by Django 5.0.4 on 2025-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(default='To apply, please fill out the application form below and upload your CV. Ensure all fields are completed before submitting your application. Application deadline:'),
        ),
    ]
