# Generated by Django 5.0.4 on 2025-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='exit_exam',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
