# Generated by Django 5.0.4 on 2025-03-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_education_cgpa_education_exit_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='exit_exam',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
