# Generated by Django 5.0.4 on 2025-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_how_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Posted', 'Posted'), ('Pending', 'Pending')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
