# Generated by Django 5.0.4 on 2025-04-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_education_cgpa_alter_education_exit_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='job',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='how_to_apply',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobcategory'),
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('Responsibility', 'Responsibility'), ('Qualification', 'Qualification'), ('Skill', 'Skill'), ('Benefit', 'Benefit')], max_length=20)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='jobs.job')),
            ],
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
