# Generated by Django 5.0.4 on 2025-04-03 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_qualification_job_remove_responsibility_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetail',
            options={'ordering': [models.Case(models.When(detail_type='Responsibility', then=models.Value(1)), models.When(detail_type='Qualification', then=models.Value(2)), models.When(detail_type='Skill', then=models.Value(3)), models.When(detail_type='Benefit', then=models.Value(4)), default=models.Value(5), output_field=models.IntegerField())]},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='show_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
