# Generated by Django 5.0.4 on 2025-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobdetail_options_job_created_at_job_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
