# Generated by Django 5.0.4 on 2025-02-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.job'),
            preserve_default=False,
        ),
    ]
