# Generated by Django 5.0.4 on 2025-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_vacancy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
