# Generated by Django 5.0.4 on 2025-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_job_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='show_experience',
            field=models.BooleanField(),
        ),
    ]
