# Generated by Django 5.0.4 on 2025-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='iconName',
            field=models.CharField(blank=True, choices=[('AiFillSketchSquare', 'AiFillSketchSquare'), ('MdOutlineMenuBook', 'MdOutlineMenuBook'), ('AiOutlinePieChart', 'AiOutlinePieChart'), ('FaChalkboardUser', 'FaChalkboardUser'), ('FaLaptopCode', 'FaLaptopCode')], max_length=200, null=True),
        ),
    ]
