# Generated by Django 5.0.4 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobcategory_iconname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='poste_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
