# Generated by Django 5.0.4 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_rename_poste_date_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='exit_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
