# Generated by Django 5.0.4 on 2025-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_education_exit_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, default='Addis Bank S.C', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, default='As per Companies Salary Scale', max_length=255),
        ),
    ]
