# Generated by Django 5.0.4 on 2025-04-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_company_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='selected_work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
