# Generated by Django 5.2.1 on 2025-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_applicant_selected_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='field_of_studies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Under Review', 'Under Review'), ('Active', 'Active'), ('Closed', 'Closed'), ('Archived', 'Archived'), ('Expired', 'Expired')], default='Draft', max_length=50),
        ),
    ]
