# Generated by Django 5.2.1 on 2025-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_field_of_studies_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
