# Generated by Django 5.2.1 on 2025-06-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.RemoveField(
            model_name='tempapplicant',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='job',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='TempApplicant',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
